### ISSUE TITLE
class_loss=0, average_loss=1

### ISSUE THREAD

**Issue by vitamin520** [Xiangtaokong/ClassSR#11]
你好，请问一下为什么我将三个分支的预训练模型修改为自己的模型，然后没有切分子图，在训练分类器的时候class_loss=0, average_loss=1？

**Comment by vitamin520** [comment]
您好，请问一下在训练分类器的时候参数fix_SR_module是不是应该设置为true呢？但是我发现当我设置为true的时候，class_loss=0, average_loss=1，当我设置为fasle的时候loss是下面的情况
21-05-12 09:57:48.121 - INFO: [epoch:  0, iter:   1,000, lr:(2.000e-04,)] l_pix: 5.1873e-02 class_loss: 1.2071e+00 average_loss: 3.5545e-01 loss: 5.3543e+01 
21-05-12 09:59:51.552 - INFO: [epoch:  0, iter:   2,000, lr:(2.000e-04,)] l_pix: 4.5431e-02 class_loss: 1.3291e+00 average_loss: 3.0894e-01 loss: 4.7022e+01 
21-05-12 10:01:55.674 - INFO: [epoch:  0, iter:   3,000, lr:(2.000e-04,)] l_pix: 4.1116e-02 class_loss: 1.4872e+00 average_loss: 2.2481e-01 loss: 4.2534e+01 
21-05-12 10:04:21.482 - INFO: [epoch:  1, iter:   4,000, lr:(2.000e-04,)] l_pix: 5.9554e-02 class_loss: 1.5422e+00 average_loss: 2.0059e-01 loss: 6.0927e+01 
21-05-12 10:06:35.722 - INFO: [epoch:  1, iter:   5,000, lr:(2.000e-04,)] l_pix: 6.5889e-02 class_loss: 1.3631e+00 average_loss: 2.9028e-01 loss: 6.7441e+01 
21-05-12 10:08:39.447 - INFO: [epoch:  1, iter:   6,000, lr:(1.999e-04,)] l_pix: 5.2064e-02 class_loss: 1.6246e+00 average_loss: 1.6442e-01 loss: 5.3369e+01 
这看起来似乎是正常的，但是我的理解是在训练分类器的时候参数fix_SR_module应该设置为true。
请问一下这个是什么原因呢？

**Comment by Xiangtaokong** [comment]
切分子图的问题：
训练的时候切分子图不会引起痕迹，大多数网络都是用小图训练的。测试时切分才可能出现切分痕迹，但overlap后实际上并不明显。ClassSR是训练测试都需要用子图片，因为ClassSR就是要切分子图片然后分类，训练时切分才能让分类器学习到如何分类子图片，测试时切分才能送到不同支路减少计算量。

loss及训练问题：
首先，如果要训练分类器，需要已经预训练过的支路（自己的模型也没问题，但前提是预训练过，能在对应类上有媲美全量数据训练的原网络的性能，参见论文方法部分）。只有这样的支路才能告诉分类器“我能处理什么类型的图片”。如果用完全没有训过的支路和完全没有训过的分类器，一般会直接收敛到全分给最复杂的那一类。

其次，训练过程是1.预训练支路 2.固定支路训分类器 3.联合训练。你的理解没有错。但如果分类器刚开始训练，出现class_loss=0, average_loss=1是合理的，因为这是分类器初始化后把所有图片分到某一类了，随着训练进行才会出现变化，慢慢学习到性能和效果的平衡，就可以正常分类了。（当然如果持续很久都是这样，说明average力度不够，就要考虑调节两个loss的比例，数据和网络结构不同，这两个loss可能需要不同比例）

最后，训练分类器时直接不固定SR支路，其实是直接进行联合训练，要知道初始化的分类器其实在“乱分”，可能对后面的SR支路产生一些影响。理论上来看很混乱，乱分的数据，又要更新SR又要更新分类器，所以不推荐这样。但根据经验这样应该也能得到不错的结果，因为一点“乱分”可能影响不大。

**Comment by vitamin520** [comment]
谢谢您的回复。受益匪浅。

**Comment by Xiangtaokong** [comment]
客气，感谢关注我们的工作~

**Comment by vitamin520** [comment]
您好，听取您的建议后，我在训练分类器的时候将参数fix_SR_module设置为true并提高了class_loss和average_loss的比重（我只是尝试了一下，并没有什么可依靠的标准），class_loss和average_loss的值不再是0和1，那我训练到什么程度才可以呢？
此外，因为我对速度这方面比较感兴趣，我使用您提供的预训练模型分别运行了test_ClassSR.py和test.py，想比较在使用了加速框架之后每张图片的推理速度是否能够加快，但是我得到的结果是相反的。请问一下您是否关注过这方面？或者是我测试速度的方法有问题吗？
非常期待您的回复。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xiangtaokong/ClassSR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月12日(星期三) 晚上10:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Xiangtaokong/ClassSR] class_loss=0, average_loss=1 (#11)





 
Closed #11.

**Comment by Xiangtaokong** [comment]
支撑文件2.1有对loss比重探究，标准是classloss接近0，同时能看到psnr上升和flops下降。
classloss的数值有代表的实际意义，比如支撑材料里到0.4，说明最大分类概率的值在80%，这个是可以计算出来的。

实际运行时间：目前classsr测试代码是串行运算的，子图片会一张一张被处理，肯定不如直接处理整张图快。我们的方法是提供一种可行方案，至于并行等如何实际部署（甚至分类方法可以不用网络，最简单网络直接用插值，分多少类，怎么并行，这一类的问题），是属于按任务适配或者工程实践的问题了。

**Comment by Xiangtaokong** [comment]
支撑文件2.1有对loss比重探究，标准是classloss接近0，同时能看到psnr上升和flops下降。
classloss的数值有代表的实际意义，比如支撑材料里到0.4，说明最大分类概率的值在80%，这个是可以计算出来的。

实际运行时间：目前classsr测试代码是串行运算的，子图片会一张一张被处理，肯定不如直接处理整张图快。我们的方法是提供一种可行方案，至于并行等如何实际部署（甚至分类方法可以不用网络，最简单网络直接用插值，分多少类，怎么并行，这一类的问题），是属于按任务适配或者工程实践的问题了。

**Comment by vitamin520** [comment]
感谢您的回复。
您说的“classsr测试代码是串行运算的，子图片会一张一张被处理，肯定不如直接处理整张图快。”，我有点不大理解为什么肯定不如直接处理整张图快，虽然分成子图，图片变多了但是一张子图相比于一张大图处理速度快很多，就算是串行，极有可能是一张图片分为4个子图（假设4个子图），而4个子图串行处理的时间快于一张大图。（仅是我的一点点理解）
此外，您论文中提到ClassSR的分支是通过减少层/通道直接从原始网络派生的。 因此，这项工作中的FLOP和运行时间具有相同的趋势。
最后，对于推理时间变慢，您觉得可能和哪些因素有关？如果想进一步提升速度，除了并行处理和简化分类器之外（因为我不是超分方向，插值可能用不到），还有哪些可能的方向呢？
非常期待您的回复。

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xiangtaokong/ClassSR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月13日(星期四) 中午1:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Xiangtaokong/ClassSR] class_loss=0, average_loss=1 (#11)





 
支撑文件2.1有对loss比重探究，标准是classloss接近0，同时能看到psnr上升和flops下降。
 classloss的数值有代表的实际意义，比如支撑材料里到0.4，说明最大分类概率的值在80%，这个是可以计算出来的。
 
实际运行时间：目前classsr测试代码是串行运算的，子图片会一张一张被处理，肯定不如直接处理整张图快。我们的方法是提供一种可行方案，至于并行等如何实际部署（甚至分类方法可以不用网络，最简单网络直接用插值，分多少类，怎么并行，这一类的问题），是属于按任务适配或者工程实践的问题了。

**Comment by Xiangtaokong** [comment]
1.（可能是常识？我在这里没有多想）比如一两个矩阵可以直接进行整体的相加，应该比分块串行（或者最极端可以想像成逐像素循环执行for）要快吧。
但这么一说，确实可以尝试一下用一个网络试试整体和分块（分块数量很多，或逐像素），我觉得整体处理肯定比分块串行快不少，因为网络也是矩阵操作。这可能跟一些底层实现有关…吧
2.论文中提到那个主要是当时kaiming大佬有个工作说flops跟时间关系不大，但那是因为不同结构引起的（activations），我们特别说明一下我们网络结构相似，flops与时间很相关，而且这个框架也可以缩减层数来减少activations。
3.不是超分可以关注剪枝重参数等等，这些是比较热门的加速方法，但我也不太了解。

（不用邮箱和github都发一遍，任选一个方式，问题合理我有时间都会回复的）
