### ISSUE TITLE
How to download DIV 8K dataset?

### ISSUE THREAD

**Issue by cravisjan97** [Xiangtaokong/ClassSR#12]

**Comment by Xiangtaokong** [comment]
Click the link https://competitions.codalab.org/competitions/22217#participate
in participate/getdata

You should register for the competition (it was held on 2020, but we can register now), then you can download DIV_8K dataset.

**Comment by qiqiing** [comment]
Can you provide a link to the downloaded DIV8K dataset? I cannot find the download link for ‘getdata’ at ‘https://competitions.codalab.org/competitions/22217#participate’. Thank you.

**Comment by cheun726** [comment]
i also could not find  the "getdata" in the download link

**Comment by Xiangtaokong** [comment]
I have uploaded processed test data. Please check readme to download.

**Comment by Xiangtaokong** [comment]
> i also could not find the "getdata" in the download link

I have uploaded processed test data. Please check readme to download.
