### ISSUE TITLE
the training process seems to be stuck

### ISSUE THREAD

**Issue by wanglixilinx** [Xiangtaokong/ClassSR#13]
Hi, @Xiangtaokong , 
   Thanks very much for your interesting work.
   Currently I want to reproduce your work.  I follow the readme and finish the data processing. while during run training command "python train_ClassSR.py -opt options/train/train_ClassSR_FSRCNN.yml",  it seems to be stuck. Can you give me some suggestions?

**Comment by Xiangtaokong** [comment]
Thanks for your attention.
Is there any output information?
The default number of out put iterations is 100, may cost several minutes.

**Comment by wanglixilinx** [comment]
hi， here is my log information:
![image](https://user-images.githubusercontent.com/54088587/120278651-1e362c00-c2e8-11eb-947f-2e703218d9b8.png)

**Comment by Xiangtaokong** [comment]
Have you waited for several minutes?（In general, each output is separated by two or three minutes）
If you have waited, I also don't know how to slove it.
I haven't met this question either.

**Comment by wanglixilinx** [comment]
thanks very much for your reply. I have solved the problem. It really needs some time to load data because there are huge numbers of images after doing data augmentation.
