### ISSUE TITLE
Problems encountered when I test and train ClassSR: Bad Results and Lack of LMDB file

### ISSUE THREAD

**Issue by DemonsHunter** [Xiangtaokong/ClassSR#16]
Recently, I am impressed by your brilliant and impressive idea and work in this paper:" ClassSR: A General Framework to Accelerate Super-Resolution Networks by Data Characteristic". It groundbreakingly accelerates SR models by classing sub-images, which attracts me a lot.
 
 Therefore, I download the released code on Github, follow the guidance in README.md, and test it. However, the results are weird. Both PSNR and SSIM are acceptable in branches testing, nevertheless, these indexes drop to ~9dB when it comes to the whole model, which confused me a lot.

 And when I try to train the model, it shows that there is a lack of LMDB file to handle validating set "Set5" during the training procedure. 2 affixed pictures demonstrate the situation. I also try to read through the above paper several times, but little things are related to this problem.

 So in a word, there are 2 problems I need your valuable help with:

1. Is there something wrong when I test the model?

2. How can I tackle LMDB issues?

 Thank you for your reading and priceless help!

{"mode":"full","isActive":false}

**Comment by Xiangtaokong** [comment]
Thanks for your attention~
1.It seems that your operations are right. You can check the settings of the test again (model path/command etc.). 
2.I will fix the code, LMDB is unnessary. Using the folder of images is OK.

**Comment by DemonsHunter** [comment]
Thank you for your reply!
About the first issue, I downsample DIV8K images 4x again by imresize function of Matlab, and the model outputs a satisfactory PSNR. But I surprisingly find that the SR image is not as the same size as the HR image. Take the 1201.img for example, HR's size is **3264*2112**, LR's size is **816*528**(3264/4=816), but the SR'size is **3264*2032**.
Is there something I miss?

**Comment by DemonsHunter** [comment]
About the second issuse, I follow your latest update, that is, to delete all "lmdb" extensions then it can begin to train. But no matter how many sizes my Set5 LR images are, it always pronounces an error:
```
Traceback (most recent call last):
  File "train.py", line 255, in <module>
    main()
  File "train.py", line 228, in main
    avg_psnr += util.calculate_psnr(sr_img, gt_img)
  File "/home/lyh/ClassSR-main/codes/utils/util.py", line 249, in calculate_psnr
    mse = np.mean((img1 - img2)**2)
ValueError: operands could not be broadcast together with shapes (120,120,3) (504,504,3)
```
So far, the GT size is 512*512, I tried 4x and 16x downsample, both of them failed, what shall I do?

**Comment by DemonsHunter** [comment]
when it comes to train the whole class SR， I am confused with DIV2K_scale_sub.
Can you explain to that?
Thank you for your help again~
![mmexport1626845680959](https://user-images.githubusercontent.com/44830115/126436307-1bff1968-05c5-48c4-8817-99592dc30837.png)

**Comment by Xiangtaokong** [comment]
1. The cropping operation will drop the bordern within 32pix (crop size:32 step:28).
2. You can use my code to generate LR-HR-paired Set5 (x4 downsample). There are some cropping bordern operations.
3. It is generated by the extract_subimages_train.py, 'scale' means the data have been augmented, sub means sub-images.

**Comment by DemonsHunter** [comment]
Thank you for your advice and explaination. 
I have another 3 questions
1. what do the crop and step mean? For example，when crop=32， step=28，then we will mark 0, 28, 56… and every mark will have a crop operation?
2. what is the validation dataset DIV2K10 of training ClassSR？
![mmexport1627007143470](https://user-images.githubusercontent.com/44830115/126731048-08610bb9-52a7-4578-91bc-a8a40f2c5ad1.png)

3. How can I train branch 2 instead of the default simplest branch 1

**Comment by Xiangtaokong** [comment]
All the answers of this three questions are in the paper&amp;code. Please solve them by yourself.
（q3：follow the paper and change the network architecture then you can put any network into classsr to become a "brabch"）

---Original---
From: ***@***.***&gt;
Date: Fri, Jul 23, 2021 10:30 AM
To: ***@***.***&gt;;
Cc: "Xiangtao ***@***.******@***.***&gt;;
Subject: Re: [Xiangtaokong/ClassSR] Problems encountered when I test and train ClassSR: Bad Results and Lack of LMDB file (#16)




 
Thank you for your advice and explaination.
 I have another 3 questions
  
 
what do the crop and step mean? For example，when crop=32， step=28，then we will mark 0, 28, 56… and every mark will have a crop operation?
 

 
what is the validation dataset DIV2K10 of training ClassSR？
 
 

 
How can I train branch 2 instead of the default simplest branch 1

**Comment by Xiangtaokong** [comment]
All the answers of this three questions are in the paper&amp;code. Please solve them by yourself.
（q3：follow the paper and change the network architecture then you can put any network into classsr to become a "branch"）
