### ISSUE TITLE
Scale 2 not working

### ISSUE THREAD

**Issue by artemkurylev** [Xiangtaokong/ClassSR#17]
Hi, first of all thanks for your work!
I have question about custom data. If I have HR images with resolution 512*384 and lowres with 256*192, and I want to convert LR->HR, what parameters should I change change in test_ClassSR_RCAN.yml for example apart from scale ( if I change only scale I've got this error:
```    

sr_img[i*step*self.scale:i*step*self.scale+patch_size*self.scale,j*step*self.scale:j*step*self.scale+patch_size*self.scale,:]+=sr_list[index]
ValueError: operands could not be broadcast together with shapes (64,64,3) (128,128,3) (64,64,3) 
```

**Comment by Xiangtaokong** [comment]
Thanks for your attention~
Sorry, ClassSR only supports x4 now. Because x4 is enough to prove its effectiveness. If you have to run x2, you need to retrain/finetune all the model.

**Comment by artemkurylev** [comment]
Ok, thank you)

**Comment by artemkurylev** [comment]
Sorry, one more question, I downsampled my images by x4 (got resolution 128 x 96) and got this error   ```sr_img[i*step*self.scale:i*step*self.scale+patch_size*self.scale,j*step*self.scale:j*step*self.scale+patch_size*self.scale,:]+=sr_list[index]
IndexError: list index out of range```

**Comment by artemkurylev** [comment]
Sorry again, it was my error
