### ISSUE TITLE
data processing for DIV8K

### ISSUE THREAD

**Issue by LeeHXAlice** [Xiangtaokong/ClassSR#18]
Hello, I have downloaded the DIV8K, I want to know how to generate the datasets (includes test2k(LR/HR), test4k(LR/HR), and test8k(LR/HR))?

**Comment by Xiangtaokong** [comment]
bicubic downsample follow the paper

we select 300 images (index 1201-1500).&nbsp;Specififically, the first two hundred images are downsampled to 2K and 4K resolution, respectively, which are used as HR images of Test2K and Test4K&nbsp;datasets. The last hundred images form the Test8K dataset.&nbsp;The LR images are also obtained by ×4 downsampling&nbsp;based on HR images.






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月25日(星期天) 晚上9:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [Xiangtaokong/ClassSR] data processing for DIV8K (#18)





 
Hello, I have downloaded the DIV8K, I want to know how to generate the datasets (includes test2k(LR/HR), test4k(LR/HR), and test8k(LR/HR))?

**Comment by Xiangtaokong** [comment]
Now I have uploaded processed test data. Please check readme to download.
