### ISSUE TITLE
data_augmentation.py

### ISSUE THREAD

**Issue by flybiubiu** [Xiangtaokong/ClassSR#2]
data_augmentation.py has some problem.
such as (_get_paths_from_images) (imresize)

**Comment by Xiangtaokong** [comment]
Thank you. I have fixed it.

**Comment by Xiangtaokong** [comment]
The data_augmentation.py only augments the GT images. Then you need to generate corresponding LR.
If you augment the GT and LR at the same time using data_augmentation.py, the size of LR and GT would be mismatched.
