### ISSUE TITLE
关于生成训练集

### ISSUE THREAD

**Issue by icey-zhang** [Xiangtaokong/ClassSR#21]
1. 请问一下，论文里“Then we densely crop 1.59M sub-images with size 32 × 32 from LR images. These sub-images are
equally divided into three classes (0.53M for each) according to their PSNR values through MSRResNet. ”
这里的1.59M户和0.53M 指的是文件大小还是其他？

2. 20-04-14 00:47:54.197 - INFO: 0558_s290            - PSNR: 26.473503 dB; SSIM: 0.751480; PSNR_Y: 27.808832 dB; SSIM_Y: 0.769544.
20-04-14 00:47:54.248 - INFO: 0558_s291            - PSNR: 26.580721 dB; SSIM: 0.764139; PSNR_Y: 27.929448 dB; SSIM_Y: 0.785679.
20-04-14 00:47:54.300 - INFO: 0558_s292            - PSNR: 25.955706 dB; SSIM: 0.801685; PSNR_Y: 27.237049 dB; SSIM_Y: 0.822988.
divide_train.log 里面scale=1的图名字直接是0558_s290，0558_s291。。。。但是extract_subimages_train.py生成的文件夹DIV2K_scale_sub里面的图名字是1_0558_s290，所以在运行divide_sub_images_train.py时会报错

3. 论文里说“To prepare the training data, we first downsample3 the original images with scaling factors 0.6, 0.7, 0.8, 0.9 to generate the HR images.” 这个意思时scale=1的图不参与训练吗？

**Comment by Xiangtaokong** [comment]
1.子图片数目
2.嗯，确实，因为当时生成的时候没有生成1x的，而是直接复制的，所以名字上是有了点问题。我改一下数据增强文件，谢谢。如果你已经生成了数据，可以重命名一下切分前图片，然后再去切分再去divide，这样应该是最快的办法。或者重新运行现在的data_augmentation.py
3.这里是数据增强，1就是原图，也包括了

**Comment by icey-zhang** [comment]
好的，我再重新处理一下，谢谢！

**Comment by icey-zhang** [comment]
您好，请问下对DIV8K 数据集下采四倍生成2K的GT，再对GT下采四倍生成LR，是这样操作嘛？2K的数据指的是第1201-1300这100张嘛？我试着用您的权重去测试，但是PSNR只有18，所以找找原因，不知道是哪一步对不上？

**Comment by Xiangtaokong** [comment]
测试集是这样的。检查一下模型加载是否正确，严格按照readme去做。使用任何测试集应该都不会是18，18在视觉上就能看出来很差。

**Comment by icey-zhang** [comment]
我测的是ClassSR-RCAN模型
这是我的配置文件
`name: test_ClassSR_RCAN
suffix: ~  # add suffix to saved images
model: ClassSR
distortion: sr
scale: 4
patch_size: 32
step: 28
crop_border: ~  # crop border when evaluation. If None(~), crop the scale pixels
gpu_ids: [3]
add_mask: False

datasets:

  test_1:
    name: test2k
    mode: LQGT_rcan
    dataroot_GT: /home/data2/zhangjiaqing/DIV2K/test2k/GT
    dataroot_LQ: /home/data2/zhangjiaqing/DIV2K/test2k/LR
  # test_2:
  #   name: test4k
  #   mode: LQGT_rcan
  #   dataroot_GT: /home/data2/zhangjiaqing/DIV2K/test4k/HR/X4
  #   dataroot_LQ: /home/data2/zhangjiaqing/DIV2K/test4k/LR/X4
  # test_3:
  #   name: test8k
  #   mode: LQGT_rcan
  #   dataroot_GT: /home/data2/zhangjiaqing/DIV2K/test8k/HR/X4
  #   dataroot_LQ: /home/data2/zhangjiaqing/DIV2K/test8k/LR/X4


#### network structures

network_G:
  which_model_G: classSR_3class_rcan
  in_nc: 3
  out_nc: 3

#### path
path:
  pretrain_model_G: /home/zhangjiaqing/zjq/ClassSR-main_paddle/codes/experiments/pre_trained_models/ClassSR_RCAN.pth
  pretrain_model_classifier: ~
  pretrain_model_G_branch1: ~
  pretrain_model_G_branch2: ~
  pretrain_model_G_branch3: ~`

**Comment by Xiangtaokong** [comment]
这个设置看起来是没有问题的，我也刚刚测试了一下，从云盘下载model，结果没有问题。
![rcan](https://user-images.githubusercontent.com/34824976/131292141-2b630a7f-27aa-4866-9412-ab3ce5c37e62.png)
唯一的问题是路径上是DIV2K，我不知道你的文件夹命名如何，但是你确认过是1201-1300了，应该是没有问题。
再check下吧~

**Comment by icey-zhang** [comment]
我的路径DIV2K，是因为我把所有数据都放在一起了，test2k是原来DIV8K出来的结果。请问下您可以直接分享一下您的数据集嘛？这是我的百度云账号851283222@qq.com

**Comment by Xiangtaokong** [comment]
是数据集的问题。这个是不对的，这是opencv默认的resize，不是bicubic，应该用这个ClassSR/codes/data_scripts/generate_mod_LR_bic.py

我明天会上传一下测试集~

**Comment by Xiangtaokong** [comment]
上传了，链接在readme里。

**Comment by icey-zhang** [comment]
十分感谢，现在测出来是正确的了，请问一下SR module单个分支的训练大概需要多少次呀，看option里有100万次，需要这么多嘛？大概set5的PSNR到多少可以停止训练呀？
https://github.com/Xiangtaokong/ClassSR/blob/main/codes/options/train/train_RCAN.yml

**Comment by Xiangtaokong** [comment]
CosineAnnealingLR_Restart一般进行一次收敛不restart就能用了，25W 50W都可以。还有建议一开始不用RCAN，训练慢而且RCAN自己本身训练的时候就容易崩（只要再在崩的地方重新开始就会没事……）

**Comment by Xiangtaokong** [comment]
我关注到你们在参加一个比赛。顺便让我发现了一个错误……train_ClassSR_RCAN.yml， train: l1w: 由250改成4
原因是RCAN原作在网络训练时没有把像素值归一到0-1区间，而其他几个网络都是0-1区间的，我们遵循了原作，所以导致l1_loss的值是其他网络的255倍左右，所以l1w应该是1000\255约等于4（我们实际训练的也是用的4），但是重构github代码时一时大意想成了1000\4，就是250了…。我已经去跟比赛方联系了

**Comment by kongdebug** [comment]
> CosineAnnealingLR_Restart一般进行一次收敛不restart就能用了，25W 50W都可以。还有建议一开始不用RCAN，训练慢而且RCAN自己本身训练的时候就容易崩（只要再在崩的地方重新开始就会没事……）

您好，想问一下RCAN一开始训练时loss在1e34附近震荡是正常的现象吗
