### ISSUE TITLE
怎样运行？

### ISSUE THREAD

**Issue by cheun726** [Xiangtaokong/ClassSR#24]

**Comment by cheun726** [comment]
您好，请问怎么在Windows环境下运行这个python train.py -opt options/train/train_FSRCNN.yml文件呀

**Comment by Xiangtaokong** [comment]
如果可以，使用linux吧。windows上没有试过

**Comment by cheun726** [comment]
您好，打扰您一下。我想使用其他基于深度学习的超分网络，我应该在您的程序上更改哪些地方呢？您可以详细的给我说一下吗？我才接触超分，问的问题比较基础，麻烦您了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiangtao ***@***.***&gt;; 
发送时间: 2021年9月1日(星期三) 下午2:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Xiangtaokong/ClassSR] 怎样运行？ (#24)





 
如果可以，使用linux吧。windows上没有试过
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Xiangtaokong** [comment]
抱歉，这段时间比较忙碌，很多具体问没办法帮忙。但如果刚学习超分，我建议可以先读一下SRCNN，至于具体代码从basicSR（SRResNet）看起，这个甚至有中文的指引，如果熟练使用，能对网络结构和框架有较好的理解。

**Comment by cheun726** [comment]
好的，谢谢您。



---原始邮件---
发件人: "Xiangtao ***@***.***&gt;
发送时间: 2021年9月1日(周三) 晚上11:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Xiangtaokong/ClassSR] 怎样运行？ (#24)




 
抱歉，这段时间比较忙碌，很多具体问没办法帮忙。但如果刚学习超分，我建议可以先读一下SRCNN，至于具体代码从basicSR（SRResNet）看起，这个甚至有中文的指引，如果熟练使用，能对网络结构和框架有较好的理解。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cheun726** [comment]
您好，我想在您的class SR的程序上添加其他的超分网络，我应该在哪里添加呀？您可以给我一些具体的建议吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xiangtaokong/ClassSR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月1日(星期三) 晚上11:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Xiangtaokong/ClassSR] 怎样运行？ (#24)





 
抱歉，这段时间比较忙碌，很多具体问没办法帮忙。但如果刚学习超分，我建议可以先读一下SRCNN，至于具体代码从basicSR（SRResNet）看起，这个甚至有中文的指引，如果熟练使用，能对网络结构和框架有较好的理解。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Xiangtaokong** [comment]
只要在arch里面添加新的网络结构，再在network.py里模仿其他网络增加调用即可
