### ISSUE TITLE
作者您好，怎么使用我自己的数据集生成divided_train.log?

### ISSUE THREAD

**Issue by zkh123456789** [Xiangtaokong/ClassSR#25]
作者您好，我想用人脸的图像来试试您的这个方法的效果。所以我想知道如何如何用我自己的人脸数据集生成divide_train.log，谢谢啦~

**Comment by Xiangtaokong** [comment]
切割训练集后，使用合适的标准网络测试所有图片的psnr，排序后选择1/3 2/3处的psnr作为阈值，使用divide_sub_images_train.py按照自己的阈值划分数据即可

**Comment by zkh123456789** [comment]
> 切割训练集后，使用合适的标准网络测试所有图片的psnr，排序后选择1/3 2/3处的psnr作为阈值，使用divide_sub_images_train.py按照自己的阈值划分数据即可

 非常感谢！

**Comment by Xiangtaokong** [comment]
不客气，感谢关注我们的工作
