### ISSUE TITLE
演示图像

### ISSUE THREAD

**Issue by muyi1729** [Xiangtaokong/ClassSR#28]
大佬您好，请问如何可视化演示图像呢？

**Comment by Xiangtaokong** [comment]
Change the 'add_mask: False' to True in test_ClassSR_xxx.yml and run testing for ClassSR.
然后在results里就是带mask的图像

**Comment by cheun726** [comment]
大佬您好 我请教您个问题。这种图用什么工具画的啊？谢谢大佬
<img width="641" alt="邮件" src="https://user-images.githubusercontent.com/72805517/138285870-42335965-b2f0-4542-bb06-b2dc8e821354.png">

**Comment by cheun726** [comment]
大佬同学，这种featuremap得可视化是怎么做的啊？麻烦您解答一下
<img width="350" alt="emai" src="https://user-images.githubusercontent.com/72805517/140859754-c6bdd063-bc48-4898-9907-99f91581b1f6.png">

**Comment by YellowOrz** [comment]
> 大佬老师，再次请教您一个问题。论文里这种Visual results图是怎么得到啊？是自己手工在大图上用红框 框出一个区域，然后手工截取吗？如果是代码实现的话，大佬老师可以给我给个demo吗？麻烦您了。 <img alt="class" width="887" src="https://user-images.githubusercontent.com/72805517/138594426-5ef2bc50-b7ac-4676-8642-90f8a8e410d5.png"> @Xiangtaokong

我发现一个可以轻松画这种图的好工具：[MulimgViewer](https://github.com/nachifur/MulimgViewer) !

**Comment by Xiangtaokong** [comment]
谢谢！如果早知道，就能省很多事了~

**Comment by Xiangtaokong** [comment]
谢谢！如果早知道就能省很多事了~
上面的feature map就是保存了网络中间输出的feature再画热力图 可能是Seaborn画的
