### ISSUE TITLE
GPU-Util  about 10%

### ISSUE THREAD

**Issue by flybiubiu** [Xiangtaokong/ClassSR#3]
<img width="1212" alt="截屏2021-03-11 下午1 39 26" src="https://user-images.githubusercontent.com/20927755/110741659-02366780-8270-11eb-9b81-10b133574de9.png">

Is this normal？

**Comment by Xiangtaokong** [comment]
Yes, the ClassSR-FSRCNN is pretty samll.

**Comment by flybiubiu** [comment]
Thx author!Nice project!
