### ISSUE TITLE
divide_train.log

### ISSUE THREAD

**Issue by 14544453895** [Xiangtaokong/ClassSR#33]
我想使用别的数据集进行训练，想问一下该文件里面的PSNR、SSIM、PSNR_Y、SSIM_Y怎么获取？

**Comment by Xiangtaokong** [comment]
从https://github.com/xinntao/BasicSR 下载一个训练好的MSRResNet（也可以自己用全量数据训），把你切割好的子图片跑一遍即可。（记得按需求重新划分阈值）
