### ISSUE TITLE
如何取消裁剪GT？

### ISSUE THREAD

**Issue by kzq666666** [Xiangtaokong/ClassSR#36]
作者您好，我用您的模型跑了一些测试代码，但生成的图都是裁剪过的，可以取消裁剪GT图吗？（我改了crop_border为none也还是会裁剪掉）

**Comment by Xiangtaokong** [comment]
是 内部裁剪了 还是裁剪掉了一些边缘 的意思？

**Comment by kzq666666** [comment]
内部裁剪掉了，比如set14第一张图GT是baboon是480x480，我跑测试代码生成的图是464x464的，可以取消这种裁剪吗

**Comment by Xiangtaokong** [comment]
没有办法取消，这个裁剪是因为，classsr会把整图裁剪成一些小图然后恢复再拼接，小图的大小是128*128 步长 16，剩下的不够一张小图，就出现了“裁剪”。

如果你只是想要图，可以直接跑RCAN之类的单模型，就不会有这个问题了

**Comment by kzq666666** [comment]
好的，明白了，非常谢谢！！
