### ISSUE TITLE
About Other Models

### ISSUE THREAD

**Issue by msx-123** [Xiangtaokong/ClassSR#37]
First of all, thank you for your excellent work!
Secondly I have some questions that I don't quite understand and would like to ask.
1. Is your proposed data feature accelerated super-resolution network applicable to any super-resolution network, because I want the framework to reduce the training computation of other networks, how can I do it?

2. If I use the framework to reduce the training computation of other networks do I need to train a pre-trained model first and how to train it?

3. I saw that the network did some data preprocessing work before training, can you explain the role of these work, why do I need to downsample the images to 0.6, 0.7, 0.8, 0.9?

4. I see that the classification model for simple, medium and complex classification is chosen by the criterion of psnr, what images are selected to calculate the psnr?

5. When testing, I see you say that some datasets are too small for crop testing, how many times the minimum dataset can be tested?

I look forward to your reply, thank you!

**Comment by Xiangtaokong** [comment]
Your email has been replied.
