### ISSUE TITLE
请问为什么要对原图下采样[1, 0.9, 0.8, 0.7, 0.6]倍

### ISSUE THREAD

**Issue by LingsiDS** [Xiangtaokong/ClassSR#38]
作者您好，我看了论文中提到先对原始数据下采样 0.9, 0.8, 0.7, 0.6，作为HR，再对这些数据下采样4倍得到LR，请问这样做是出于什么原因呢？

**Comment by Xiangtaokong** [comment]
是底层视觉中常见的数据增强操作。从SRCNN开始就这么做，不同尺度的相同内容其实包含不同特征（如100*100的脸 和 10*10的同一张脸）。

**Comment by LingsiDS** [comment]
好的明白了，谢谢~

> 是底层视觉中常见的数据增强操作。从SRCNN开始就这么做，不同尺度的相同内容其实包含不同特征（如100_100的脸 和 10_10的同一张脸）。
