### ISSUE TITLE
the output resolution differs from the GT

### ISSUE THREAD

**Issue by cherrysnower** [Xiangtaokong/ClassSR#4]
hello, I tested 100 images from DIV2k(index from 800--900),  use ClassSR-FSRCNN pretrained model, it seems that the output HR images(1232x1048, 0801_x4.png)'s revolution differs from the GT(2040x1356, 0801.png) . so is there something with me or the code ?

**Comment by Xiangtaokong** [comment]
Please check your setting. I tested '0801.png' and obtained the SR with 2032X1248 right now.  The size (2032X1248) is different from GT (2040x1356) because ClassSR will crop LR into 32x32. But the '1232x1048' is a wrong size.
