### ISSUE TITLE
关于多倍率的问题

### ISSUE THREAD

**Issue by chh13502** [Xiangtaokong/ClassSR#5]
请问可以使用这个网络进行除了x4以外其他倍率的SR操作吗？如果可以，大致需要做怎样的修改呢；如果不行，需要做什么别的工作呢？

**Comment by chh13502** [comment]
还有一个问题，在testClassSR时，数据集是需要自己构造吗？

**Comment by Xiangtaokong** [comment]
在github上放出的不行。但方法可以适用于各种分辨率，需要按论文中的方法重新训练符合要求的支路，再重新训练ClassSR，或者使用预训练的模型进行finetune。没做多倍率实验的原因是X4已经足以证明方法有效。

如果要复现文中测试Test2K，Test4K，Test8K，需要下载DIV8K再下采样，下采样操作在generate_mod_LR_bic.py 改一下路径就好。如果不是为了复现文章，那就用自己想测的test图片就好。

**Comment by chh13502** [comment]
明白了，非常感谢！

**Comment by Xiangtaokong** [comment]
客气，感谢关注我们的工作~
