### ISSUE TITLE
How to create a divide_rain.log folder？

### ISSUE THREAD

**Issue by vitamin520** [Xiangtaokong/ClassSR#7]
Hello, I have now generated sub-images. I want to use the generated sub-images to train my models of different branches. How can I create a divide_train.log file suitable for my model?

**Comment by Xiangtaokong** [comment]
There are many ways to generate it. 
First, you can run the test.py (comment out the codes of PSNR_y and SSIM, using a suitable model and testing the generated sub-images) directly to generate a result log file, it is the 'divide_train.log'.
Then, you can set the thresholds in divide.py by your needs. (We set the threshold by sorting the PSNR results of MSRResNet and getting the one-third/ two-third PSNR values. It is suitable for most cases.)
Finally, you are also encouraged to calculate other suitable indicators of the generated sub-images such as gradient. In that way, you need to change the divide.py file to divide the sub-images by your own indicators.

**Comment by vitamin520** [comment]
Thank you very much for your reply.
Is it necessary to ensure that the results obtained by MSRResNet (such as the subjective and objective effects of image enhancement) are better than the results obtained by the model to be accelerated?
In other words, what criteria is used to select the PSNR obtained by the MSRResNet test to divide the pictures into three categories?



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xiangtaokong/ClassSR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月7日(星期三) 上午10:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Xiangtaokong/ClassSR] How to create a divide_rain.log folder？ (#7)





 
There are many ways to generate it.
 First, you can run the test.py (comment out the codes of PSNR_y and SSIM, using a suitable model and testing the generated sub-images) directly to generate a result log file, it is the 'divide_train.log'.
 Then, you can set the thresholds in divide.py by your needs. (We set the threshold by sorting the PSNR results of MSRResNet and getting the one-third/ two-third PSNR values. It is suitable for most cases.)
 Finally, you are also encouraged to calculate other suitable indicators of the generated sub-images such as gradient. In that way, you need to change the divide.py file to divide the sub-images by your own indicators.

**Comment by Xiangtaokong** [comment]
No, it is not necessary. The standard model (such as MSRResNet) is not related to the accelerated model, it just is used to preliminary divide data to provide SR branches a good starting point.

We chose the thresholds by the PSNR values which can divide the sub-images into three equal parts.

**Comment by vitamin520** [comment]
Thank you for your reply.
Are there any limitations between the true value of the training set and low-quality images? I can train with the datasets you provided, but if I modify it to my datasets, an error will be reported. The true value of my training set is the same as the low-quality image size. The error is as follows:
Traceback (most recent call last):
  File "/home/liuxiaoyan/tempdisk/PycharmProjects/ClassSR-try/codes/train_ClassSR.py", line 351, in <module>
    main()
  File "/home/liuxiaoyan/tempdisk/PycharmProjects/ClassSR-try/codes/train_ClassSR.py", line 154, in main
    for _, train_data in enumerate(train_loader): 
  File "/home/liuxiaoyan/Downloads/python3/envs/pytorch1_7/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/liuxiaoyan/Downloads/python3/envs/pytorch1_7/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/liuxiaoyan/Downloads/python3/envs/pytorch1_7/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/liuxiaoyan/Downloads/python3/envs/pytorch1_7/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/liuxiaoyan/Downloads/python3/envs/pytorch1_7/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/liuxiaoyan/Downloads/python3/envs/pytorch1_7/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/liuxiaoyan/Downloads/python3/envs/pytorch1_7/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/liuxiaoyan/Downloads/python3/envs/pytorch1_7/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/liuxiaoyan/Downloads/python3/envs/pytorch1_7/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 76, 0] at entry 0 and [3, 0, 0] at entry 1.

**Comment by Xiangtaokong** [comment]
Sorry, what is the "ture value"?

**Comment by vitamin520** [comment]
Sorry, it is the"ground truth".
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xiangtaokong/ClassSR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月9日(星期五) 上午10:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Xiangtaokong/ClassSR] How to create a divide_rain.log folder？ (#7)





 
Sorry, what is the "ture value"?

**Comment by Xiangtaokong** [comment]
So you use the GT and LR with the same size？
You should generate LR(down sample x4) from GT using generate_LR.py.



---Original---
From: ***@***.***&gt;
Date: Fri, Apr 9, 2021 22:31 PM
To: ***@***.***&gt;;
Cc: "Xiangtao ***@***.******@***.***&gt;;
Subject: Re: [Xiangtaokong/ClassSR] How to create a divide_rain.log folder？ (#7)




 Sorry, it is the"ground truth". 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "Xiangtaokong/ClassSR"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年4月9日(星期五) 上午10:06 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [Xiangtaokong/ClassSR] How to create a divide_rain.log folder？ (#7) 
 
 
 
 
 
   
 Sorry, what is the "ture value"?
