### ISSUE TITLE
当运行extract_subimages_test.py出现错误

### ISSUE THREAD

**Issue by ymtupup** [Xiangtaokong/ClassSR#8]
E:\Anaconda\envs\torch11\python.exe D:/迅雷下载/ClassSR-main/codes/data_scripts/extract_subimages_test.py
process GT...
mkdir [D:/迅雷下载/ClassSR-main/data0/xtkong/data/DIV2K_valid_HR_sub/GT] ...
[                              ] 0/100, elapsed: 0s, ETA:
Start...
All subprocesses done.
process LR...
mkdir [D:/迅雷下载/ClassSR-main/data0/xtkong/data/DIV2K_valid_HR_sub/LR] ...
[                              ] 0/100, elapsed: 0s, ETA:
Start...
All subprocesses done.
Traceback (most recent call last):
  File "D:/迅雷下载/ClassSR-main/codes/data_scripts/extract_subimages_test.py", line 143, in <module>
    main()
  File "D:/迅雷下载/ClassSR-main/codes/data_scripts/extract_subimages_test.py", line 66, in main
    assert len(data_util._get_paths_from_images(save_GT_folder)) == len(
  File "D:\迅雷下载\ClassSR-main\codes\data\util.py", line 31, in _get_paths_from_images
    assert images, '{:s} has no valid image file'.format(path)
AssertionError: D:/迅雷下载/ClassSR-main/data0/xtkong/data/DIV2K_valid_HR_sub/GT has no valid image file

**Comment by ymtupup** [comment]
请作者给点提示，感谢！

**Comment by Xiangtaokong** [comment]
你需要先下载数据集到指定的文件夹，或者修改文件路径。
刚入门可以去学习basicSR那个项目，有中文指引

**Comment by ymtupup** [comment]
如图所示，进图条不动，显示子进程完成，可是DIV2K_valid_sub/GT里没有任何提取的子图啊

**Comment by Xiangtaokong** [comment]
进度条不动是因为没有进行切割
可能的原因有：
1.路径含有中文
2.使用的是windows，路径写法可能需要有些不同
因为整套代码没有在windows下运行过，我也不能确定出了什么问题，建议用linux

**Comment by ymtupup** [comment]
好了解决了，我用2080成功解决。。。。

**Comment by Xiangtaokong** [comment]
切图片没用到gpu…应该是用linux就ok
