### ISSUE TITLE
iteration over a 0-d tensor

### ISSUE THREAD

**Issue by nivetha-123** [Xiangtaokong/ClassSR#9]
Traceback (most recent call last):
  File "train_ClassSR.py", line 347, in <module>
    main()
  File "train_ClassSR.py", line 277, in main
    model.test()
  File "/home/dsm/ClassSR-main/codes/models/ClassSR_model.py", line 199, in test
    self.num_res = self.print_res(type_res)
  File "/home/dsm/ClassSR-main/codes/models/ClassSR_model.py", line 352, in print_res
    for i in torch.max(type_res, 1)[1].data.squeeze():
  File "/home/dsm/anaconda3/envs/nsw2/lib/python3.7/site-packages/torch/tensor.py", line 451, in __iter__
    raise TypeError('iteration over a 0-d tensor')
TypeError: iteration over a 0-d tensor
While running the training code in classSR it occurs an error on this file train_ClassSR.py in line277.How could i solve this .Thanks in advance

**Comment by Xiangtaokong** [comment]
Please check and make sure that the model has read the data. I guss it is caused by some mistakes during reading data.

**Comment by Xiangtaokong** [comment]
You are encouraged to use validation dataset(DIV2K_valid, index 801-810). Otherwise you can not observe the training process. Of course, you can also train without validation dataset by commenting out the code of validation in train_xxx.py.

**Comment by liangmu-666** [comment]
> Traceback (most recent call last):
> File "train_ClassSR.py", line 347, in
> main()
> File "train_ClassSR.py", line 277, in main
> model.test()
> File "/home/dsm/ClassSR-main/codes/models/ClassSR_model.py", line 199, in test
> self.num_res = self.print_res(type_res)
> File "/home/dsm/ClassSR-main/codes/models/ClassSR_model.py", line 352, in print_res
> for i in torch.max(type_res, 1)[1].data.squeeze():
> File "/home/dsm/anaconda3/envs/nsw2/lib/python3.7/site-packages/torch/tensor.py", line 451, in **iter**
> raise TypeError('iteration over a 0-d tensor')
> TypeError: iteration over a 0-d tensor
> While running the training code in classSR it occurs an error on this file train_ClassSR.py in line277.How could i solve this .Thanks in advance

Hellow！I also met the same question.If you have solved this question?

**Comment by YUvUY** [comment]
> > Traceback (most recent call last):
> > File "train_ClassSR.py", line 347, in
> > main()
> > File "train_ClassSR.py", line 277, in main
> > model.test()
> > File "/home/dsm/ClassSR-main/codes/models/ClassSR_model.py", line 199, in test
> > self.num_res = self.print_res(type_res)
> > File "/home/dsm/ClassSR-main/codes/models/ClassSR_model.py", line 352, in print_res
> > for i in torch.max(type_res, 1)[1].data.squeeze():
> > File "/home/dsm/anaconda3/envs/nsw2/lib/python3.7/site-packages/torch/tensor.py", line 451, in **iter**
> > raise TypeError('iteration over a 0-d tensor')
> > TypeError: iteration over a 0-d tensor
> > While running the training code in classSR it occurs an error on this file train_ClassSR.py in line277.How could i solve this .Thanks in advance
> 
> Hellow！I also met the same question.If you have solved this question?

Have you sloved this problem? I have the same one , please/
